### ISSUE TITLE
RxJava 3 Retrofit Adapter

### ISSUE THREAD

**Issue by nidhinprathap** [abhinav0612/Pokemon#1]
Hi,
Why wasn't the official RxJava3 Retrofit adapter not used?
https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava3
https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-290-2020-05-20

**Comment by bugcacher** [comment]
When I started the project it wasn't available and many developers suggested using the one I used but since now it is available you can use the official one. Same goes with Room support for RxJava 3 it is not available at the moment.

**Comment by nidhinprathap** [comment]
Cool . Thanks for the post.

**Comment by bugcacher** [comment]
You're Welcome.
